version: 0.0
os: windows

files:
  - source: /
    destination: C:\Users\Administrator\Desktop\ball

file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: server_start.sh
      timeout: 300
  ApplicationStop:
    - location: server_stop.sh
      timeout: 300
