version: 0.0
os: windows

files:
  - source: /
    destination: C:\Users\Administrator\Desktop\ball

hooks:
  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
