version: 0.0
os: windows

files:
  - source: /
    destination: C:\Users\Administrator\Desktop\ball

file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: \before-install.bat
      timeout: 900
  AfterInstall:
    - location: server_start.bat
      timeout: 300
  ApplicationStop:
    - location: server_stop.bat
      timeout: 300
